CREATE TABLE IF NOT EXISTS drive (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_t(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);